# Generated by Django 3.1.4 on 2020-12-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerName',
        ),
    ]
