# Generated by Django 3.1.4 on 2020-12-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20201223_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'Statistics'},
        ),
    ]
