# Generated by Django 3.1.4 on 2020-12-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_playerdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerData',
        ),
    ]
